<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Episode extends \AppBundle\Entity\Episode implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Episode' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Episode' . "\0" . 'title', '' . "\0" . 'AppBundle\\Entity\\Episode' . "\0" . 'sumView', '' . "\0" . 'AppBundle\\Entity\\Episode' . "\0" . 'season', '' . "\0" . 'AppBundle\\Entity\\Episode' . "\0" . 'realisator', '' . "\0" . 'AppBundle\\Entity\\Episode' . "\0" . 'actor');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Episode' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Episode' . "\0" . 'title', '' . "\0" . 'AppBundle\\Entity\\Episode' . "\0" . 'sumView', '' . "\0" . 'AppBundle\\Entity\\Episode' . "\0" . 'season', '' . "\0" . 'AppBundle\\Entity\\Episode' . "\0" . 'realisator', '' . "\0" . 'AppBundle\\Entity\\Episode' . "\0" . 'actor');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Episode $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', array($title));

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', array());

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setSumView($sumView)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSumView', array($sumView));

        return parent::setSumView($sumView);
    }

    /**
     * {@inheritDoc}
     */
    public function getSumView()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSumView', array());

        return parent::getSumView();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeason(\AppBundle\Entity\Season $season = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeason', array($season));

        return parent::setSeason($season);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeason()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeason', array());

        return parent::getSeason();
    }

    /**
     * {@inheritDoc}
     */
    public function addRealisator(\AppBundle\Entity\Realisator $realisator)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRealisator', array($realisator));

        return parent::addRealisator($realisator);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRealisator(\AppBundle\Entity\Realisator $realisator)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRealisator', array($realisator));

        return parent::removeRealisator($realisator);
    }

    /**
     * {@inheritDoc}
     */
    public function getRealisator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRealisator', array());

        return parent::getRealisator();
    }

    /**
     * {@inheritDoc}
     */
    public function addActor(\AppBundle\Entity\Actor $actor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addActor', array($actor));

        return parent::addActor($actor);
    }

    /**
     * {@inheritDoc}
     */
    public function removeActor(\AppBundle\Entity\Actor $actor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeActor', array($actor));

        return parent::removeActor($actor);
    }

    /**
     * {@inheritDoc}
     */
    public function getActor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActor', array());

        return parent::getActor();
    }

}
